### PR TITLE
Fix iamrole should be a string.

### PR DESCRIPTION
**Pull request by vicentgodella**
I was getting an error because iamrole is not a string.
I just added a explicit conversion from bytes to string.

### CODE REVIEW

**Comment by vorlock** [comment]
This change looks like making sense, tho could you post error you've got which triggered this PR?
I'm asking as I've never seen it and I'm just curious.

**Comment by vicentgodella** [comment]
Sorry, but I didn't save the error message. It was something related to the type of iamrole attribute, because it wasn't a string, it was a bytes.

I can't reproduce it right now because I'm using the fixed code.

**Comment by fred-vogt** [comment]
@vicentgodella @vorlock - also seeing this after updating, error below w/backtrace

`TypeError: Cannot mix str and non-str arguments`

```
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 596, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 383, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 191, in get_credentials
    self.iamrole))
  File "/usr/lib/python3.6/urllib/parse.py", line 508, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/usr/lib/python3.6/urllib/parse.py", line 120, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by fred-vogt** [comment]
@vorlock - I think this happens when using Python 3 such as ubuntu 18.04, 20.04

**Comment by drob** [comment]
Thank you for fixing this! (And for a great lib.) Would it be possible to get a new version released with this fix included?

**Pull request merged**
